### PR TITLE
fix(grpc): fix gRPC deprecation warning

### LINKED ISSUE #48: DeprecationWarning on startup and CLI usage
Due to generated code from '.proto' files containing `new Buffer() node v10 shows a `DeprecationWarning`
on startup and when calling gRPC commands from `walli-cli`.

We should keep an eye out for the next release of [grpc-node](https://github.com/grpc/grpc-node) and [grpc-tools](https://www.npmjs.com/package/grpc-tools).
Another option would be to install `node-tools` from [github](https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools).

### PR DESCRIPTION
**Pull request by michael1011**
Closes #48 

@ImmanuelSegol I don't have Windows installed so could you please find and test a Windows equivalent for `sed`?

@dopetard I read that the `sed` command is a little bit different on macOS. Could you please pull down this branch and run `npm i && npm run proto` and tell me if that command fails?

### CODE REVIEW

**Comment by dopetard** [comment]
It did fail. @michael1011 Here is the log 

https://gist.github.com/dopetard/fdd6699d94ab966b793ff0c9f977d3e6

**Comment by michael1011** [comment]
The error you are experiencing is because a prebuilt version of gRPC is being downloaded when running `npm i`. Can you make sure you are connected to a VPN when installing? @dopetard

**Comment by ImmanuelSegol** [comment]
@michael When I get home I'll try to use PowerShell commands to replace `new Buffer`.

**Comment by dopetard** [comment]
@michael1011 The problem persists with VPN. I will look into it deeply soon.

**Pull request merged**
